# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('subtitle', models.CharField(max_length=256, verbose_name='subtitle')),
                ('slug', models.SlugField(max_length=80, verbose_name='slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/articles/thumbnail/', verbose_name='thumbnail')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('contents', models.TextField(verbose_name='contents')),
                ('authors', models.ManyToManyField(to='authorProfile.AuthorProfile', verbose_name='authors')),
            ],
        ),
    ]
