# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=256, verbose_name='lastname')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='article.User', verbose_name='authors'),
        ),
    ]
