# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170130_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(default='game design', max_length=256, verbose_name='category'),
        ),
    ]
